### ISSUE TITLE
Unable to open a file archived with 7zip.

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#173]
**Describe the bug**
Importing a comic encoded with  7zip fails.

**To Reproduce**
1. Navigate to the comic import page.
1. Load the contents of a directory that includes a comic archived in 7zip format.
1. The comic cover does not load.
1. The backend throws an exception.

**Expected behavior**
The comic should be loaded, and the system should be able to get the cover and then import the comic.

**Additional context**
The exception thrown is:
```
2020-03-08 12:43:02.807 ERROR 42551 --- [nio-7171-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106) ~[na:1.8.0_144]
	at org.comixed.adaptors.archive.AbstractArchiveAdaptor.getFirstImageFileName(AbstractArchiveAdaptor.java:294) ~[classes/:na]
	at org.comixed.service.file.FileService.getImportFileCover(FileService.java:68) ~[classes/:na]
	at org.comixed.controller.file.FileController.getImportFileCover(FileController.java:100) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
```

**Comment by bareheiny** [comment]
That looks suspiciously like the other error I’d occasionally see when trying to import a WebP formatted comic.

**Comment by mcpierce** [comment]
@bareheiny Are you comics CB7 files?

**Comment by bareheiny** [comment]
No - CBZ, but they are archived with 7zip (as part of my increasingly complicated work flow for processing comics prior to importing them into CX).

I haven't had any problems with 7ziped archives before...but when I started playing with WebP, I either struck the WebP issue or (less frequently) the nested "exception is java.lang.NullPointerException" you've mentioned.

I hadn't raised it as a bug because it seemed (at the time) to be related to WebP importing.

**Comment by bareheiny** [comment]
I just got the message again when I opened CX and navigated to the library page - where the only entry is for an unprocessed (comix entry exists, but no page hashes) WebP archive.

**Comment by mcpierce** [comment]
Reopening this ticket as not fixed, since the solution added a new set of issues.

**Comment by mcpierce** [comment]
I found the fix for this, and have done more testing to ensure it works. It fixes the slowdown of loading images. However, it reverts the comic import to showing the first physical (as opposed to first sorted) image from an archive during the import process. We can revisit loading the image for a file to be imported later.
