### ISSUE TITLE
Error when creating the folder

### ISSUE THREAD

**Issue by morpheus200** [comixed/comixed#1827]
**Describe The Bug**
When I consolidate the comics, I get a "trailing char" error. In this case, it is because there is a space after the series name. Would it be possible to check if there is a space at the end when saving and remove it automatically? As a check routine, so to speak.

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Series name contains a blank at the end.
2. Consolidate the comic 
3. A folder could not be created, due to the blank at the end.

**Expected Behavior**
The blank at the end should be removed by "Save changes to comic" as an error routine.

**ComiXed Runtime Environment**

 - [x ] Windows
 - [ ] Linux (any distro)
 - [ ] MacOS
 - [ ] Docker (if so, please select the host OS)

**ComiXed Build Detail:**
The code was built from a branch named 73a304f6a03f607e140b2aedbc07a7059beb8ea8
The code was built on December 17, 2023 at 6:05:26 PM GMT+1.
Code was built on a machine named fv-az665-196.
The code was marked with a Build version of 1.6.6-1.
The latest commit hash on the source branch is 73a304f6a03f607e140b2aedbc07a7059beb8ea8.
This commit was created on December 17, 2023 at 5:48:00 PM GMT+1.
Commit Message
Changed the release version to 1.6.6-1 [#1682]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:h2:file:~/.comixed/comixed

**Additional Context**
2023-12-19 13:00:22.620 ERROR 39452 --- [     CX-Jarvis9] o.c.b.c.processors.MoveComicProcessor    : Failed to move comics

java.nio.file.InvalidPathException: Trailing char < > at index 53: \\192.168.177.27\hdd2\comics\library\Marvel\Daredevil \2007\Daredevil  v2007 #0001.cbz
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:172) ~[na:na]
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[na:na]
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[na:na]
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[na:na]
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229) ~[na:na]
        at java.base/java.io.File.toPath(File.java:2310) ~[na:na]
        at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1304) ~[commons-io-2.7.jar!/:2.7]
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:797) ~[commons-io-2.7.jar!/:2.7]
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:747) ~[commons-io-2.7.jar!/:2.7]
        at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2019) ~[commons-io-2.7.jar!/:2.7]
        at org.comixedproject.adaptors.file.FileAdaptor.moveFile(FileAdaptor.java:97) ~[comixed-adaptors-1.6.6-1.jar!/:1.6.6-1]
        at org.comixedproject.batch.comicbooks.processors.MoveComicProcessor.process(MoveComicProcessor.java:83) ~[comixed-batch-1.6.6-1.jar!/:1.6.6-1]
        at org.comixedproject.batch.comicbooks.processors.MoveComicProcessor.process(MoveComicProcessor.java:44) ~[comixed-batch-1.6.6-1.jar!/:1.6.6-1]
        at org.springframework.batch.core.step.item.SimpleChunkProcessor.doProcess(SimpleChunkProcessor.java:134) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.step.item.SimpleChunkProcessor.transform(SimpleChunkProcessor.java:319) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:210) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:77) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.15.jar!/:5.3.15]
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:152) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:413) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:136) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:320) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:149) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
        at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

**Comment by mcpierce** [comment]
@morpheus200 This has been added to the codebase. The solution will go through the database and will trim the publisher, series, volume, issue number, title, description, and notes of any leading or trailing spaces. It will also, going forward, trim those columns whenever the values are updated in the database as part of CX's scraping process.

It won't, though, update the metadata files in the existing comics or any external metadata file. Those will need to be updated by selecting the comic books and telling the server to update those files after you run the next release.

Once you've verified this is working as desired, please feel free to close this ticket as resolved. Or, if it doesn't, please post a comment that the issue persists.

**Comment by morpheus200** [comment]
Thanks
