### ISSUE TITLE
Purging comics is not working and sends a error message

### ISSUE THREAD

**Issue by fanzines** [comixed/comixed#2185]
**Describe The Bug**
When marking comics for removal and using the purge comics functionality nothing will happen. A error message will then appear in the batch processing section that says:

org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:803)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:757)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:152)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:255)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:369)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:206)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:140)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:240)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:229)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:153)
	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:418)
	at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:132)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:317)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:157)
	at java.base/java.lang.Thread.run(Thread.java:833)

**To Reproduce The Bug**
1. Mark a comic as removed
2. Go to the library section of the options and purge comics that are marked for removal
3. Go to batch processing to see the error message
4. See that none of the comics have been removed

**Expected Behavior**
That hitting purge comics would remove the ones marked.

**ComiXed Runtime Environment**

 - [ ] Windows
 - [ ] Linux (any distro)
 - [ ] MacOS
 - [ X] Docker through DSM on a synology NAS

**ComiXed Build Detail:**

The code was built from a branch named ab9f23175db635cc904afcc5c09caf7200f95d7b
The code was built on 2024-10-22T11:50:54.000+00:00.
Code was built on a machine named fv-az1144-789.
The code was marked with a Build version of 2.2.1-2.
The latest commit hash on the source branch is ab9f23175db635cc904afcc5c09caf7200f95d7b.
This commit was created on 2024-10-22T11:38:32.000+00:00.
Commit Message
Changed the release version to v2.2.1-2 [#2157]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:h2:file:~/.comixed/comixed
Using Java 17.0.2+8-86 (Oracle Corporation) running on Linux v4.4.302+ (amd64)

**Screenshots**
![image](https://github.com/user-attachments/assets/7e177974-8b7c-4cd1-a33e-2d0110eebea0)

**Comment by mcpierce** [comment]
@fanzines I noticed this in your build details:

```The database URL being used is jdbc:h2:file:~/.comixed/comixed```

This issue *may* be related to using the H2 embedded DB, which isn't supported for regular usage. Are you able to test this using a database like MySQL, Mariah, or Postgres?

**Comment by fanzines** [comment]
Ah okay I had missed the bit of documentation that it was best to use MySQL or so on. I can confirm mark for deletion and the purge is functioning how I would expect it to now. Thanks for the help!

**Comment by fanzines** [comment]
Actually I stand corrected. I thought I had managed to set up a mysql database properly but when I tested it again it seems I actually was still using H2 embedded. I added my application.properties file but now am getting a error message that says " Failed to load remote library state. " whenever I do anything. Also when I try to import comics it doesn't do anything. I am sure this is just a setup thing I messed up though I can see the tables comixed made in my database so it was able to write to it at some point. Any ideas on what that error means?

**Comment by mcpierce** [comment]
When you look at the logs, does it show any SQL errors? Or any errors running migrations on startup?

**Comment by fanzines** [comment]
Here is the log after a startup without clicking on anything:
024-11-05T00:09:23.199Z  INFO 14 --- [ComiXed] [main] org.comixedproject.ComiXedApp            : Starting ComiXedApp v2.2.1-2 using Java 17.0.2 with PID 14 (/app/comixed-release/bin/comixed-app-2.2.1-2.jar started by root in /app)
2024-11-05T00:09:23.218Z  INFO 14 --- [ComiXed] [main] org.comixedproject.ComiXedApp            : No active profile set, falling back to 1 default profile: "default"
2024-11-05T00:09:50.338Z  INFO 14 --- [ComiXed] [main] org.comixedproject.ComiXedApp            : Started ComiXedApp in 28.551 seconds (process running for 29.655)

What was in the Log After I get the message:

2024-11-05T00:13:17.593Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-1] o.c.rest.app.ReleaseController           : Getting latest release details
2024-11-05T00:13:17.670Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-3] o.c.rest.user.UserController             : Loading current user: dcosborne97@gmail.com
2024-11-05T00:13:17.679Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-2] o.c.rest.admin.ConfigurationController   : Getting feature enabled setting: library.blocked-pages-enabled
2024-11-05T00:13:17.923Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-4] o.c.rest.library.LibraryController       : Loading the current library state
2024-11-05T00:13:18.254Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-9] o.c.r.c.ComicBookSelectionController     : Loading comic book selections
2024-11-05T00:13:18.255Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-3] o.c.rest.library.LastReadController      : Loading last read entries for dcosborne97@gmail.com
2024-11-05T00:13:18.256Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-10] o.c.rest.library.LastReadController      : Loading unread comic book count for user: email=dcosborne97@gmail.com
2024-11-05T00:13:18.261Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-2] o.c.rest.batch.BatchProcessesController  : Getting the status of all batch processes
2024-11-05T00:13:18.269Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-8] o.c.r.comicpages.BlockedHashController   : Load all blocked pages
2024-11-05T00:13:18.350Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-4] o.c.rest.lists.ReadingListController     : Getting reading lists: user=dcosborne97@gmail.com

What is added when trying to import:
2024-11-05T00:14:47.015Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-10] o.c.rest.comicfiles.ComicFileController  : Getting all comic files: root=/incoming maximum=UNLIMITED
2024-11-05T00:14:47.238Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-2] o.c.rest.user.UserController             : Setting user preference: dcosborne97@gmail.com preference.import.root-directory="/incoming"
2024-11-05T00:14:47.238Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-4] o.c.rest.user.UserController             : Setting user preference: dcosborne97@gmail.com preference.import.maximum-results="0"
2024-11-05T00:14:52.053Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-10] o.c.rest.comicfiles.ComicFileController  : Importing comic files

Browser console shows this: error: "Internal Server Error"
​​
path: "/api/library/state"
​​
status: 500
​​
timestamp: "2024-11-05T00:13:18.170+00:00"

**Comment by fanzines** [comment]
Alright update. I ended up switching from using mysql to using postgres and everything is working fine now. I assume I just set something up wrong originally. The mark for deletion and purge is working so it was to do with using the h2 embedded. Thanks for all the help!
