### ISSUE TITLE
Library re-scan failing with "thread starvation or clock leap detected" error.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#242]
Earlier today I started a library re-scan.  After a period of time, CX threw an error and failed.  Re-opening CX a while later, the re-scan appears to have picked up where it ended...and after around 50 minutes it threw the same error:

Partial log:

2020-04-13 19:51:15.834  WARN 11004 --- [ Jarvis-ComiXed] o.h.h.internal.ast.QueryTranslatorImpl   : HHH000104: firstResult/maxResults specified with collection fetch; applying in memory!
2020-04-13 20:35:15.785  WARN 11004 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=43m58s751ms754µs201ns).
2020-04-13 20:36:37.903  INFO 11004 --- [ Jarvis-ComiXed] o.h.e.internal.DefaultLoadEventListener  : HHH000327: Error performing load command : org.hibernate.HibernateException: Unable to access lob stream

org.hibernate.HibernateException: Unable to access lob stream
	at org.hibernate.type.descriptor.java.DataHelper.extractString(DataHelper.java:270) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.type.descriptor.java.StringTypeDescriptor.wrap(StringTypeDescriptor.java:75) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.type.descriptor.java.StringTypeDescriptor.wrap(StringTypeDescriptor.java:22) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.type.descriptor.sql.ClobTypeDescriptor$1.doExtract(ClobTypeDescriptor.java:44) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]

**Comment by mcpierce** [comment]
Hrm, the thread starvation/clock leap message sounds familiar.

What is the database setup being used, the built-in H2 or an external RDBMS? The error message seems to indicate that CX couldn't connect to the DB, as the lines in the stacktrace are all from below the application's code. 

Just did a quick google search on "Thread starvation or clock leap detected" and this part doesn't seem to be an issue; i.e., if you're running on a laptop (and looking at the time stamp in the stacktrace) it looks like it was put to sleep for about 44 minutes (the difference between the first and second lines in the trace). So that part's nothing to be concerned about.

Are you able to consistently cause this, or did it only come up once?

**Comment by bareheiny** [comment]
Built-in H2 DB.

I've managed to trigger it twice (somehow) - I'm running CX on a Surface, so it may be a sleep issue.  Although it was plugged in, and I've changed the power settings to never sleep when on mains....it's entirely possible I didn't acutally switch the power on.

Will try again once I've finished re-importing my library.
